# Generated by Django 5.2.8 on 2025-11-11 12:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("hero_section", 8)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subtitle text", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for hero section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for primary button", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for secondary button", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for primary button", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for secondary button", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Screen"),
                                ("medium", "Medium Height"),
                                ("small", "Small Height"),
                            ],
                            "help_text": "Hero section height",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("primary_button_text", 3),
                                ("secondary_button_text", 4),
                                ("primary_button_link", 5),
                                ("secondary_button_link", 6),
                                ("height", 7),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
