# Generated by Django 5.2.8 on 2025-11-11 13:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [("hero_section", 8), ("stats", 13), ("impact_statistic", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subtitle text", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for hero section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for primary button", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for secondary button", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for primary button", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for secondary button", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Screen"),
                                ("medium", "Medium Height"),
                                ("small", "Small Height"),
                            ],
                            "help_text": "Hero section height",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("primary_button_text", 3),
                                ("secondary_button_text", 4),
                                ("primary_button_link", 5),
                                ("secondary_button_link", 6),
                                ("height", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("users", "Users"),
                                ("utensils", "Utensils"),
                                ("heart", "Heart"),
                                ("globe", "Globe"),
                            ],
                            "help_text": "Icon representing the statistic",
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main numeric value",
                            "max_length": 20,
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Description of the statistic",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional suffix like '+'",
                            "max_length": 5,
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_name", 9),
                                ("number", 10),
                                ("label", 11),
                                ("suffix", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title for the statistics section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for the statistics section",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {"help_text": "List of impact statistics"},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 14),
                                ("section_subtitle", 15),
                                ("stats", 16),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
