# Generated by Django 5.2.8 on 2025-11-12 02:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "ordering": ["title"],
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
        ),
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero_section", 8),
                    ("section_header", 10),
                    ("stats", 15),
                    ("impact_statistic", 19),
                    ("project_card", 26),
                    ("project_cards", 30),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading text", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional subtitle text", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for hero section",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for primary button", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for secondary button", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for primary button", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link for secondary button", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Screen"),
                                ("medium", "Medium Height"),
                                ("small", "Small Height"),
                            ],
                            "help_text": "Hero section height",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("primary_button_text", 3),
                                ("secondary_button_text", 4),
                                ("primary_button_link", 5),
                                ("secondary_button_link", 6),
                                ("height", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Center-align the header text",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("centered", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("users", "Users"),
                                ("utensils", "Utensils"),
                                ("heart", "Heart"),
                                ("globe", "Globe"),
                            ],
                            "help_text": "Icon representing the statistic",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main numeric value",
                            "max_length": 20,
                            "required": True,
                        },
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Description of the statistic",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional suffix like '+'",
                            "max_length": 5,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_name", 11),
                                ("number", 12),
                                ("label", 13),
                                ("suffix", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title for the statistics section",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Subtitle for the statistics section",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (15,),
                        {"help_text": "List of impact statistics"},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 16),
                                ("section_subtitle", 17),
                                ("stats", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Project image", "required": True},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project title",
                            "max_length": 200,
                            "required": True,
                        },
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Project location",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Project description", "required": True},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Active", "Active"),
                                ("Ongoing", "Ongoing"),
                                ("Completed", "Completed"),
                            ],
                            "help_text": "Project status",
                        },
                    ),
                    25: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional link to project details page",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 20),
                                ("title", 21),
                                ("location", 22),
                                ("description", 23),
                                ("status", 24),
                                ("link", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the projects section",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Optional subtitle for the projects section",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {"help_text": "List of project cards"},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 27),
                                ("section_subtitle", 28),
                                ("projects", 29),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Composable content blocks for the home page.",
                null=True,
            ),
        ),
    ]
